apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
 name: ark-eks-cluster
 region: us-west-2

vpc:
 clusterEndpoints:
   publicAccess:  true
   privateAccess: true

nodeGroups:
 - name: ng-1
   instanceType: t2.micro
   desiredCapacity: 2
